---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: src/dev-logs/Drafts
  label: Drafts
  create: all
  match: "**/*.md"
  templates:
  - post
- type: directory
  path: src/dev-logs
  label: Dev Logs
  create: all
  match: "**/*md"
- type: directory
  path: src/posts
  label: Posts
  create: all
  match: "**/*.md"
upload_dir: src/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
